import {StyleSheet} from "react-native";

export const useStyles = () => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#fff",
    },
    card: {
      backgroundColor: "#219ebc",
      borderRadius: 10,
      padding: 10,
      margin: 10,
      height: 150,
      shadowColor: "#000",
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 3,
    },
    cardContent: {
      flexDirection: "column",
      justifyContent: "space-evenly",
      height: "100%",
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: "bold",
      letterSpacing: 1,
      lineHeight: 25,
      color: "#FFF",
      textAlign: "center",
    },
    cardText: {
      fontSize: 13,
      color: "#1d3557",
      textAlign: "center",
      fontWeight: "500",
    },
    content: {
      flex: 0.5,
      justifyContent: "center",
      paddingHorizontal: 20,
    },
    forgotPasswordContainer: {
      alignItems: "flex-end",
    },
    form: {
      alignItems: "center",
      backgroundColor: "rgba(235, 235, 245, 0.6)",
      borderRadius: 8,
      flexDirection: "row",
      height: 40,
      paddingHorizontal: 16,
      marginVertical: 10,
    },
    safeAreaView: {
      flex: 1,
    },
    subtitle: {
      color: "rgba(235, 235, 245, 0.6)",
      fontSize: 20,
      fontWeight: "400",
      lineHeight: 15,
      textAlign: "left",
      marginBottom: 20,
    },
    create: {
      color: "rgba(235, 235, 245, 0.6)",
      fontSize: 17,
      fontWeight: "400",
      lineHeight: 15,
      textAlign: "center",
      marginTop: 20,
    },
    textButton: {
      color: "#FFFFFF",
      fontSize: 18,
      textAlign: "center",
      marginHorizontal: "auto",
      fontWeight: "400",
    },
    textInput: {
      color: "#1d3557",
      flex: 1,
    },
    title: {
      color: "#FFF",
      fontSize: 24,
      textAlign: "center",
      paddingVertical: 10,
      fontWeight: "300",
    },
    loginContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
      backgroundColor: "#219ebc",
    },
    loginTitle: {
      color: "#000",
      fontSize: 40,
      textAlign: "center",
      paddingVertical: 10,
      fontWeight: "600",
      lineHeight: 2,
      marginVertical: 35,
    },
    loginInput: {
      width: "100%",
      padding: 10,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: "#ccc",
      borderRadius: 5,
    },
    loginButton: {
      backgroundColor: "#023047",
      padding: 2,
      borderRadius: 5,
      alignSelf: "center",
      width: "50%",
      alignItems: "center",
      marginTop: 15,
    },
    loginButtonText: {
      color: "#fff",
      fontSize: 18,
      margin: 10,
    },
    searchInput: {
      backgroundColor: "#83c5be",
      padding: 10,
      width: "50%",
      marginBottom: 0,
      marginHorizontal: 10,
      borderRadius: 5,
      color: "#023047",
      fontSize: 15,
      marginVertical: 20,
    },
    wrapHeader: {
      display: "flex",
      flexDirection: "row",
      height: 150,
      justifyContent: "space-evenly",
      alignItems: "center",
    },
    filterBox: {
      flexDirection: "column",
      marginTop: 1,
    },
    innerBox: {
      backgroundColor: "#023047",
      borderRadius: 5,
    },
    filterText: {
      color: "#FFF",
      padding: 5,
      fontWeight: "400",
    },
    disconnectButton: {
      backgroundColor: "#83c5be",
      padding: 10,
      borderRadius: 5,
      alignSelf: "center",
      width: "auto",
      alignItems: "center",
      marginTop: 15,
    },
    disconnectText: {
      color: "#023047",
    },
  });
};
